services:
  - type: web
    name: data-analysis-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn analysisapp.wsgi:application --log-file -"
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "data-analysis-dashboard-qqn9.onrender.com,.onrender.com"
      - key: DJANGO_SECRET_KEY
        generator: SECRET
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: "data_analysis_dashboard"
